<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="JunitXml.TestLogger" PrivateAssets="all" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VoiceCraft.Client\VoiceCraft.Client\VoiceCraft.Client.csproj" />
    <ProjectReference Include="..\VoiceCraft.Core\VoiceCraft.Core.csproj" />
    <ProjectReference Include="..\VoiceCraft.Network\VoiceCraft.Network.csproj" />
    <ProjectReference Include="..\VoiceCraft.Server\VoiceCraft.Server.csproj" />
    <ProjectReference Include="..\VoiceCraft.Server.Runtime\VoiceCraft.Server.Runtime.csproj" />
    <ProjectReference Include="..\VoiceCraft.Web\VoiceCraft.Web.csproj" />
  </ItemGroup>
</Project>
